name: .NET

on: workflow_dispatch
  # push:
  #   branches: main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    # - name: Setup .NET
    #   uses: actions/setup-dotnet@v3
    #   with:
    #     dotnet-version: 7.0.x
    # - name: Run program
    #   run: dotnet run
    # - name: Build
    #   run: dotnet build --no-restore
    
    - name: Build the Docker image
      # working-directory: sample1/
      run: docker build .

    # - name: Log into Docker Hub
    #   uses: docker/login-action@v3
    #   with:
    #     username: ${{ secrets.DOCKERHUB_USERNAME }}
    #     password: ${{ secrets.DOCKERHUB_TOKEN }}
    
